name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose Terraform action"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # Required for OIDC

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Google Cloud auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: gcp-github-actions-connection/simple-terraform

      - name: Terraform Action
        run: |
          if [ "${{ github.event.inputs.action }}" = "plan" ]; then
            terraform plan
          else
            terraform apply -auto-approve
          fi
        working-directory: gcp-github-actions-connection/simple-terraform
