name: Terraform multiple env Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (dev|tst|stg)"
        required: true
        type: choice
        options:
          - dev
          - tst
          - stg
      action:
        description: "Terraform action"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # Needed for OIDC to GCP

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Cloud Auth (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="prefix=gcp-infra/${{ github.event.inputs.environment }}"
        working-directory: gcp-github-actions-connection/terraform-multiple-env-infra

      - name: Terraform Action
        run: |
          if [ "${{ github.event.inputs.action }}" = "plan" ]; then
            terraform plan \
              -var-file="envs/${{ github.event.inputs.environment }}/terraform.tfvars"
          else
            terraform apply -auto-approve \
              -var-file="envs/${{ github.event.inputs.environment }}/terraform.tfvars"
          fi
        working-directory: gcp-github-actions-connection/terraform-multiple-env-infra
